# Generated by Django 6.1.1 on 2026-09-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIModel',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='idx_chat_history_user_chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
