# Generated by Django 6.1.1 on 2026-09-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_deleted_at_chatmessage_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_id',
            field=models.CharField(max_length=50),
        ),
    ]
