# Generated by Django 6.1.1 on 2026-09-16 05:13

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatmessage_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_id',
            field=models.CharField(default=chatbot.models.generate_uuid_str, max_length=50),
        ),
    ]
